# 1. Usa immagine base con Java 17 JDK Alpine
FROM eclipse-temurin:17-jdk-alpine

# 2. Copia il jar prodotto nella cartella target nel container e rinominalo app.jar
COPY target/bibliotecaScolastica-service-0.0.1-SNAPSHOT.jar app.jar

# 3. Espone la porta 8080 (default Spring Boot)
EXPOSE 8080

# 4. Comando per avviare l'app
ENTRYPOINT ["java", "-jar", "/app.jar"]
